/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUSUF IFTHIKAR
 */
public class Adminpg extends javax.swing.JFrame {

    private static final String username="root";
    private static final String password="root";
    private static final String dataConn="jdbc:mysql://localhost:3306/vehicalrental";
    
    Connection sqlConnAdmin=null;
    PreparedStatement pstAdmin=null,pstAdmin1=null;
    ResultSet rsAdmin=null,rsAdmin1=null;
    
    
    //User tab
    PreparedStatement pstAdmin2=null,pstAdmin3=null;
    ResultSet rsAdmin2=null,rsAdmin3=null;
    
    //Rental tab
    PreparedStatement pstAdmin4=null,pstAdmin5=null;
    ResultSet rsAdmin4=null,rsAdmin5=null;
   
    
    
    /**
     * Creates new form Adminpg
     */
    public Adminpg() {
        initComponents();
        autogenCarRegNo();
        //vehical Registration tab and vehiReg table
        tablevegregupdate();
        //User tab and Users table
        updatetableUser();
        //Rental Tab and Rental table
        updatetabelrental();
        updatereturnedvehitable1();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        addvehicalbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtregno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcarregno = new javax.swing.JTextField();
        txtmake = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comavailability = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        userbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userbtn.setText("User");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });

        bookbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookbtn.setText("Rental");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        addvehicalbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addvehicalbtn.setText("Register Vehical");
        addvehicalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvehicalbtnActionPerformed(evt);
            }
        });

        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addvehicalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(userbtn)
                .addGap(18, 18, 18)
                .addComponent(bookbtn)
                .addGap(18, 18, 18)
                .addComponent(addvehicalbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 554));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Delete User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Email", "PhoneNo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Vehicale-ID", "fee", "datetaken", "due -date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Renting");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicale-ID", "CustNIC", "Due-Date", "NoofDaysElapsed", "Fine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Return");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel2)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Vehicale Registration");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Car RegNo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Make");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Model");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Availability");

        addbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        delbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delbtn.setText("DELETE");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        editbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editbtn.setText("Update");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CarRegNo", "Make", "Model", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        comavailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        javax.swing.GroupLayout txtregnoLayout = new javax.swing.GroupLayout(txtregno);
        txtregno.setLayout(txtregnoLayout);
        txtregnoLayout.setHorizontalGroup(
            txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtregnoLayout.createSequentialGroup()
                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtregnoLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(82, 82, 82)
                        .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtregnoLayout.createSequentialGroup()
                                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcarregno, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(txtmake)
                                    .addComponent(txtmodel))
                                .addGap(48, 48, 48)
                                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(txtregnoLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel3)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtregnoLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        txtregnoLayout.setVerticalGroup(
            txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtregnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcarregno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn)
                    .addComponent(delbtn))
                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtregnoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtmake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(txtregnoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(editbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(txtregnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comavailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", txtregno);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, -26, 770, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void updatereturnedvehitable1(){
    
        int colcount;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin5=sqlConnAdmin.prepareStatement("select * from returnvehi");
            rsAdmin5=pstAdmin5.executeQuery();
            
            ResultSetMetaData rd=(ResultSetMetaData) rsAdmin5.getMetaData();
            colcount=rd.getColumnCount();
            DefaultTableModel df=(DefaultTableModel)jTable4.getModel();
            df.setRowCount(0);//Set Row count if not when updated it will show another copy of the entire dataagain inside the tbale
            
            while (rsAdmin5.next()){
                Vector v2=new Vector();
                for(int i=1;i<colcount;i++){
                    v2.add(rsAdmin5.getString("CarNo"));
                    v2.add(rsAdmin5.getString("CustomerID"));
                    v2.add(rsAdmin5.getString("due_date"));
                    v2.add(rsAdmin5.getString("elap"));
                    v2.add(rsAdmin5.getString("fine"));
                }
                df.addRow(v2);
            }
  
        } catch (Exception e) {
            
            
        }
    
    }
 
    public void updatetabelrental(){
    
        int colcount;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin4=sqlConnAdmin.prepareStatement("select * from Rental");
            rsAdmin4=pstAdmin4.executeQuery();
            
            ResultSetMetaData rd=(ResultSetMetaData) rsAdmin4.getMetaData();
            colcount=rd.getColumnCount();
            DefaultTableModel df=(DefaultTableModel)jTable3.getModel();
            df.setRowCount(0);//Set Row count if not when updated it will show another copy of the entire dataagain inside the tbale
            
            while (rsAdmin4.next()){
                Vector v4=new Vector();
                for(int i=1;i<colcount;i++){
                    v4.add(rsAdmin4.getString("CustomerID"));
                    v4.add(rsAdmin4.getString("CarNo"));
                    v4.add(rsAdmin4.getString("fee"));
                    v4.add(rsAdmin4.getString("date"));
                    v4.add(rsAdmin4.getString("due"));
                }
                df.addRow(v4);
            }
  
        } catch (Exception e) {
            
            
        }

    }
    
    
    
    //Update table for User tab
    public void updatetableUser(){
        int colcounti;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin2=sqlConnAdmin.prepareStatement("select * from Users");
            rsAdmin2=pstAdmin2.executeQuery();
            
            ResultSetMetaData rd=(ResultSetMetaData) rsAdmin2.getMetaData();
            colcounti=rd.getColumnCount();
            DefaultTableModel df=(DefaultTableModel)jTable2.getModel();
            df.setRowCount(0);//Set Row count if not when updated it will show another copy of the entire dataagain inside the tbale
            
            while (rsAdmin2.next()){
                Vector v3=new Vector();
                for(int i=1;i<colcounti;i++){
                    v3.add(rsAdmin2.getString("Username"));
                    v3.add(rsAdmin2.getString("password"));
                    v3.add(rsAdmin2.getString("Email"));
                    v3.add(rsAdmin2.getString("PhoneNumber"));
                }
                df.addRow(v3);
            }
  
        } catch (Exception e) {
            
            
        }
    
    }

    public void tablevegregupdate(){
    
        int colcount;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin=sqlConnAdmin.prepareStatement("select * from vehicalReg");
            rsAdmin=pstAdmin.executeQuery();
            
            ResultSetMetaData rd=(ResultSetMetaData) rsAdmin.getMetaData();
            colcount=rd.getColumnCount();
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);//Set Row count if not when updated it will show another copy of the entire dataagain inside the tbale
            
            while (rsAdmin.next()){
                Vector v2=new Vector();
                for(int i=1;i<colcount;i++){
                    v2.add(rsAdmin.getString("CarNo"));
                    v2.add(rsAdmin.getString("Make"));
                    v2.add(rsAdmin.getString("Model"));
                    v2.add(rsAdmin.getString("Availability"));
                }
                df.addRow(v2);
            }
  
        } catch (Exception e) {
            
            
        }

    }
    
   
    //Function for auto generatio or auto increament the carRegNo 
    public void autogenCarRegNo(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            //Statment created to exacute SQL queary
            Statement s1=sqlConnAdmin.createStatement();
            
            rsAdmin1=s1.executeQuery("select Max(CarNo) from vehicalReg");
            rsAdmin1.next();
            rsAdmin1.getString("Max(CarNo)");
            
            if(rsAdmin1.getString("Max(CarNo)")==null){
                
                txtcarregno.setText("V0001");
               
            }
            else {
            
                long id=Long.parseLong(rsAdmin1.getString("Max(CarNo)").substring(2,rsAdmin1.getString("Max(CarNo)").length()));
                id++;
                txtcarregno.setText("V0"+String.format("%03d",id));
                
            }
   
        } catch (Exception e) {
            
            
        }
    }

//User tab btn
    
    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
               
    }//GEN-LAST:event_userbtnActionPerformed
//Booking tab btn
    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_bookbtnActionPerformed
//Vehicale tab btn
    private void addvehicalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvehicalbtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_addvehicalbtnActionPerformed
//Going back to login page 
    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        loogin l2=new loogin();
        l2.show();
        dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    
    //Add button vehical registation Tab
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String carregno=txtcarregno.getText();
        String mak=txtmake.getText();
        String mod=txtmodel.getText();
        String av=comavailability.getSelectedItem().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin1=sqlConnAdmin.prepareStatement("INSERT INTO vehicalReg (CarNo, Make, Model,Availability)VALUES (?,?,?,?)");
            pstAdmin1.setString(1,carregno);
            pstAdmin1.setString(2,mak);
            pstAdmin1.setString(3,mod);
            pstAdmin1.setString(4,av);
            
            pstAdmin1.executeUpdate();
            JOptionPane.showMessageDialog(this,"Vehicale Added");
            txtmake.setText("");
            txtmodel.setText("");
            comavailability.setSelectedItem(-1);
            txtmake.requestFocus();
            
            autogenCarRegNo();
            tablevegregupdate();
            
        } catch (Exception e) {
            
            
        }
       
    }//GEN-LAST:event_addbtnActionPerformed

//On click on the entry of the data on jtable It will refill the 
    //The entries on the tex box which was selected form the table
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
         int selectindex=jTable1.getSelectedRow();
         
         txtcarregno.setText(d1.getValueAt(selectindex,0).toString());
         txtmake.setText(d1.getValueAt(selectindex,1).toString());
         txtmodel.setText(d1.getValueAt(selectindex,2).toString());
         comavailability.setSelectedItem(d1.getValueAt(selectindex,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked
//Edit btn when clicked it will upodate the entry
    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d2=(DefaultTableModel)jTable1.getModel();
        int selectedindex=jTable1.getSelectedRow();
        
        
        try {
            
            String id=d2.getValueAt(selectedindex,0).toString();
            String make=txtmake.getText();
            String model=txtmodel.getText();
            String stat=comavailability.getSelectedItem().toString();
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
            pstAdmin1=sqlConnAdmin.prepareStatement("update vehicalReg set Make=?, Model=?,Availability=? where CarNo=?");
            pstAdmin1.setString(1,make);
            pstAdmin1.setString(2,model);
            pstAdmin1.setString(3,stat);
            pstAdmin1.setString(4,id);
            pstAdmin1.executeUpdate();
            JOptionPane.showMessageDialog(this,"Entry Updated");
            tablevegregupdate();
            
            
        } catch (Exception e) {
            System.out.println("Error");
        }
      
        
        
        
    }//GEN-LAST:event_editbtnActionPerformed
//Delete Entry in the jTable1
    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d3=(DefaultTableModel)jTable1.getModel();
        int selectedindex=jTable1.getSelectedRow();
        
        
        String id=d3.getValueAt(selectedindex,0).toString();
        int resultofoption=JOptionPane.showConfirmDialog(this,"Confirm Deleteion of Entry","Confirmation!",JOptionPane.YES_NO_OPTION);
        if (resultofoption==JOptionPane.YES_OPTION){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
                pstAdmin1=sqlConnAdmin.prepareStatement("delete from vehicalReg where CarNo=?");
                pstAdmin1.setString(1,id);
                pstAdmin1.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entru Deleted");
                tablevegregupdate();   
                
            } catch (Exception e) {
            }
        
        }else{
            JOptionPane.showMessageDialog(this,"Cancelled");  
        }
    }//GEN-LAST:event_delbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d3=(DefaultTableModel)jTable2.getModel();
        int selectedindex=jTable2.getSelectedRow();
        String id=d3.getValueAt(selectedindex,0).toString();
        
        
        int resultofoption=JOptionPane.showConfirmDialog(this,"Confirm Deleteion of EMployee User","Confirmation!",JOptionPane.YES_NO_OPTION);
        if (resultofoption==JOptionPane.YES_OPTION){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConnAdmin=DriverManager.getConnection(dataConn,username,password);
                pstAdmin3=sqlConnAdmin.prepareStatement("delete from Users where Username=?");
                pstAdmin3.setString(1,id);
                pstAdmin3.executeUpdate();
                JOptionPane.showMessageDialog(this,"User Deleted");
                updatetableUser();   
                
            } catch (Exception e) {
            }
        
        }else{
            JOptionPane.showMessageDialog(this,"Cancelled");  
        }                                        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton addvehicalbtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JComboBox<String> comavailability;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JTextField txtcarregno;
    private javax.swing.JTextField txtmake;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JPanel txtregno;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
