/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.PreparedStatement;
//hello
/*import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;*/

import java.sql.DriverManager;

import java.sql.ResultSet;
/*import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;*/
import javax.swing.JOptionPane;
/*import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;*/





/**
 *
 * @author YUSUF IFTHIKAR
 */
public class loogin extends javax.swing.JFrame {
    
    private static final String username="root";//user name of Mysql
    private static final String password="root";//password for mysql
    private static final String dataConn="jdbc:mysql://localhost:3306/vehicalrental";//url to mysql database vehicale rental
    
    
    //This variable is used to store the connection to the database once it's established
    Connection sqlConn=null;//sqlConn of type Connection and itialized its value to null
    //used to execute SQL queries in a more secure and efficient manner.
    PreparedStatement pst=null;
    //used to execute SQL queries in a more secure and efficient manner.
    ResultSet rs=null;
   
    
    

    /**
     * Creates new form loogin
     */
    public loogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textusername = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        textuserpassord = new javax.swing.JPasswordField();
        loginbtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 190, -1, -1));
        getContentPane().add(textusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 172, 30));

        signup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signup.setText("New User");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, -1));

        textuserpassord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textuserpassordActionPerformed(evt);
            }
        });
        getContentPane().add(textuserpassord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        loginbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginbtn1.setText("Login");
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 109, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-icon.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        //When clicked logg in to the account
        SignUp s1=new SignUp();
        s1.show();
        dispose();
    
    }//GEN-LAST:event_signupActionPerformed

    private void textuserpassordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textuserpassordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textuserpassordActionPerformed

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.mysql.jdbc.Driver");//Use to establish connection with Mysql
            sqlConn=DriverManager.getConnection(dataConn,username,password);//Use to establish connection with the Database vehicale rental
            
            String loginusername=textusername.getText();
            String loginpassword=textuserpassord.getText();
            
            pst=sqlConn.prepareStatement("select * from Users where Username=? and Password=?");
            pst.setString(1,loginusername);
            pst.setString(2,loginpassword);
            
            
            /*executes the prepared statement and retrieves the result 
            set into the rs variable. The result set contains the rows that match 
            the criteria defined in the SQL query.*/
            rs=pst.executeQuery();
            
            
            /*checks whether there is at least one row in the result set. If rs.next() returns true, 
            it means there's at least one row to process, and the code within the if block will be execute*/
            if (rs.next()== true){
                
                /*Inside the if block, you retrieve the "Username" and "Password" values from the current row in the result set:*/
                //the username and password below are to get string form the database login
               String retrievedUsername = rs.getString("Username");
               String retrievedPassword = rs.getString("Password");
               
               if("admin".equals(retrievedUsername) && "admin".equals(retrievedPassword)){
                      Adminpg admin=new Adminpg();
                      admin.show();
                      dispose();
               }
               //if the above is not True it opens the Userpg
               else{       
                   User user=new User();
                   user.show();
                   dispose();        
               }
            }
            
            // its false it mean no resuls
            else if (rs.next()==false){
                JOptionPane.showMessageDialog(this, "username or password Incorrect");
                textusername.setText("");
                textuserpassord.setText("");
            }
        sqlConn.close();
  
        } catch (Exception e) {            
            System.out.println(e);
        }
   
        
    }//GEN-LAST:event_loginbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JButton signup;
    private javax.swing.JTextField textusername;
    private javax.swing.JPasswordField textuserpassord;
    // End of variables declaration//GEN-END:variables
}
